# load the wine dataset
# using the PCA estimator reduce the data into 1 dimension
# show the components and explained variance ratio
# print the shape of the reduced data

In [5]:
import pandas as pd
wine = pd.read_csv("wine.csv")
wine

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [7]:
wine.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [10]:
features = wine.drop("Wine",axis=1)
features.head()

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [12]:
#shape of original data
features.shape

(178, 13)

In [14]:
#reduction of dimensions
import seaborn as sns
from sklearn.decomposition import PCA
model = PCA(n_components=1)
model.fit(features)

PCA(n_components=1)

In [15]:
features_1D = model.transform(features)

In [16]:
features_1D

array([[ 318.56297929],
       [ 303.09741966],
       [ 438.06113292],
       [ 733.24013935],
       [ -11.5714285 ],
       [ 703.23119174],
       [ 542.97158087],
       [ 548.40185984],
       [ 298.0368628 ],
       [ 298.04955314],
       [ 763.07971194],
       [ 532.94322773],
       [ 572.83441039],
       [ 402.92535829],
       [ 800.05339386],
       [ 563.245578  ],
       [ 533.37965064],
       [ 383.31759108],
       [ 933.1183875 ],
       [  98.40317748],
       [  33.593594  ],
       [  23.14643754],
       [ 288.09303022],
       [ 267.98151253],
       [  98.01988577],
       [  83.49874396],
       [ 447.92559622],
       [ 537.91916502],
       [ 168.2104676 ],
       [ 288.00824708],
       [ 538.0264521 ],
       [ 768.09293886],
       [ 243.1507509 ],
       [ 488.60128005],
       [ 348.231007  ],
       [ 173.07995743],
       [ 133.28642355],
       [ 358.01855918],
       [ 273.04443152],
       [  13.64300211],
       [  48.42964225],
       [ 287.88409217],
       [ 348.09534818],
       [ -66.81465539],
       [ 138.22700988],
       [ 333.25480583],
       [ 318.11184847],
       [ 238.11148508],
       [ 313.11991539],
       [ 513.18774802],
       [ 402.93901716],
       [ 517.92896327],
       [ 443.26641129],
       [ 628.28607099],
       [ 313.39761268],
       [ 373.33329122],
       [ 223.41710636],
       [ 523.0728514 ],
       [ 538.18209732],
       [-227.03269045],
       [ -66.850122  ],
       [-296.82443689],
       [-116.97047258],
       [-327.0591256 ],
       [-391.75248644],
       [ -68.90576044],
       [-245.21252398],
       [-237.24141029],
       [   3.29615599],
       [ -27.96612073],
       [ 123.13013831],
       [-337.10412249],
       [-275.09602588],
       [ 238.71675655],
       [ 139.09405664],
       [-318.8763289 ],
       [-355.06025251],
       [-246.63359745],
       [   3.77168966],
       [-283.84224764],
       [-469.05935031],
       [ -33.13133925],
       [-117.29039201],
       [-232.13298838],
       [-226.95329942],
       [-296.85215173],
       [-252.04639193],
       [-185.10885737],
       [ -67.18075184],
       [-122.4313264 ],
       [-267.1853332 ],
       [-297.10441468],
       [-252.21388507],
       [-457.02221494],
       [-401.85127409],
       [ 191.18339677],
       [-121.27917775],
       [-319.0882728 ],
       [ -87.08029256],
       [-341.04090017],
       [ -36.93161455],
       [-185.07371349],
       [-308.88238661],
       [-332.08929638],
       [ -75.15313775],
       [-432.00974192],
       [-237.20669709],
       [-259.14836773],
       [-434.95778011],
       [ -66.99069577],
       [-184.73643853],
       [-422.04287362],
       [-139.81866316],
       [-313.06094816],
       [-362.12963311],
       [-340.11500621],
       [-252.10947206],
       [-401.69597348],
       [-375.17109237],
       [-183.09792918],
       [-121.94524135],
       [-281.53456912],
       [-381.82677823],
       [-367.08938005],
       [-367.1571747 ],
       [-369.10360097],
       [-395.07883646],
       [-281.03036871],
       [-405.0612878 ],
       [-167.23764182],
       [-116.47300036],
       [-216.78453998],
       [-186.91511197],
       [-146.76952962],
       [ -97.1329736 ],
       [ -51.98204687],
       [ -27.09793075],
       [-231.95153407],
       [-167.07624576],
       [-156.86804454],
       [-146.94648958],
       [  32.90429275],
       [-226.92620969],
       [-197.00434749],
       [ 108.3126773 ],
       [  83.11826261],
       [-332.19583999],
       [-122.12609209],
       [ -97.01938927],
       [-196.6248066 ],
       [-246.44919923],
       [-266.62878805],
       [-321.57074094],
       [ -71.89765871],
       [-106.8166178 ],
       [ -22.0202568 ],
       [-267.03173231],
       [ 132.99984125],
       [ -86.91399859],
       [-127.06128965],
       [-227.06883575],
       [ -66.75543118],
       [-176.76509843],
       [ -71.76839793],
       [-132.04824836],
       [-227.07784455],
       [ -51.68950646],
       [ -62.08501112],
       [   3.18276465],
       [-116.67481805],
       [-236.92120794],
       [-277.08357826],
       [ -87.02740263],
       [  -6.98021096],
       [   3.13160468],
       [  88.45807369],
       [  93.45624185],
       [-186.94319027]])

In [18]:
#shape of reduced data
features_1D.shape

(178, 1)

In [19]:
#print eigen vectors
print(model.components_)

[[ 1.65926472e-03 -6.81015556e-04  1.94905742e-04 -4.67130058e-03
   1.78680075e-02  9.89829680e-04  1.56728830e-03 -1.23086662e-04
   6.00607792e-04  2.32714319e-03  1.71380037e-04  7.04931645e-04
   9.99822937e-01]]

In [23]:
#print explained variance ratio
print(model.explained_variance_ratio_)

[0.99809123]